config/routes.rb
Rails.application.routes.draw do

  get 'about/we'

  namespace :blogs do
  resources :posts do
    resources :comments, only: [:create]
  end
    resources :post_sorts, only: [:index, :new, :create, :destroy]
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
                 sessions: 'users/sessions',               #登录／退出
                 registrations: 'users/registrations',
                 passwords: 'users/passwords'
                   },
             path_names: {    #为动作设置别名
                 sign_in: 'login',       #登录别名
                 sign_out: 'logout',
                 password: 'secret',
                              confirmation: 'verification',
                              registration: 'register'

             }
  devise_scope :user do
    get 'login',  to: 'users/sessions#new'
    get 'register', to: 'users/registrations#new'
    get 'secret', to: 'users/passwords#new'
  end

  root to: "welcome#home"

end

app/models/blogs.rb
module Blogs
  def self.table_name_prefix
    'blogs_'
  end
end

app/models/blogs/comment.rb
class Blogs::Comment < ActiveRecord::Base
  belongs_to :user, counter_cache: 'blogs_comment_count',
             inverse_of: :blogs_comments

  belongs_to :blogs_post, :class_name => 'Blogs::Post',
      foreign_key: :post_id,
      inverse_of: :blogs_comments,
      counter_cache: 'comment_count'
end

app/models/blogs/post.rb
class Blogs::Post < ActiveRecord::Base
  belongs_to :user, counter_cache: :post_count,
             inverse_of: :blogs_posts

  has_many :blogs_comments, :class_name => 'Blogs::Comment',
      inverse_of: :blogs_post

  belongs_to :blogs_sort, :class_name => 'Blogs::Sort',
             counter_cache: :post_count,
      inverse_of: :blogs_posts,
      foreign_key: :sort_id
end

app/models/blogs/sort.rb
class Blogs::Sort < ActiveRecord::Base

  has_many :blogs_posts, :class_name => 'Blogs::Post',
             inverse_of: :blogs_sort


  belongs_to :user,counter_cache: :blogs_sort_count,
      inverse_of: :blogs_sorts
end

app/controllers/blogs/comments_controller.rb
class Blogs::CommentsController < ApplicationController
  def create
    @blog_comment = Blogs::Comment.new(create_params)
    @post = Blogs::Post.find(params[:post_id])
    @blog_comment.blogs_post = @post
    @blog_comment.user = current_user
    respond_to do |format|
      if @blog_comment.save

        format.json{ render json: [@blog_comment,current_user], status: :created }
      else
        format.html
      end
    end
  end
  private
  def create_params
    params.require(:blogs_comment).permit(:comment_content)
  end
end

app/controllers/blogs/post_sorts_controller.rb
class Blogs::PostSortsController < ApplicationController
  before_action :set_post_sort, only: [:destroy]
  def index
    @post_sorts = Blogs::Sort.all
  end

  def new
    @blogs_post_sort = Blogs::Sort.new
  end

  def create
    @post_sort = Blogs::Sort.new(create_params)
    respond_to do |format|
      if @post_sort.save
        flash[:alert]= "博客分类　#{@post_sort.name} 添加成功。"

        format.js
        format.json{ render json: @post_sort, status: :created}
      else
        format.js
      end
    end
  end

  def destroy
    respond_to do |format|
      if @post_sort.delete
        flash[:alert]= "分类　#{@post_sort.name} 已删除！"
        format.json{ render json: @post_sort, status: :created}
      else
        format.js
      end
    end
  end

  private
  def set_post_sort
    @post_sort = Blogs::Sort.find(params[:id])
  end

  def create_params
    params.require(:blogs_sort).permit(:name)
  end
end

app/controllers/blogs/posts_controller.rb
class Blogs::PostsController < ApplicationController
  before_action :set_post, only: [:show,:edit, :update]
  before_action :set_blog_sort, only: [:new, :edit]
  #load_and_authorize_resource
  def index
    @posts = Blogs::Post.all
  end

  def new
    @post = Blogs::Post.new
    @post_sorts = Blogs::Sort.all
  end

  def create
    @post = Blogs::Post.new(create_params)
    @post.user = current_user
    if @post.save
      redirect_to blogs_post_path(@post),notice: '恭喜，创建成功！'
    else
      redirect_to :back, flash: {error: '对不起，创建失败，你必须重新检测以下。'}
    end
  end
  def edit
    @post_sorts = Blogs::Sort.all
    render :new
  end
  def update
    if @post.update(update_params)
      redirect_to action: :show, notice: "您的博客　#{@post.title}　更新成功！"
    else
      redirect_to :back, alert: '更新失败！'
    end
  end
  def show
    @title = TitleStyle.new(@post.title,'show-blog_title','http://img.blog.163.com/photo/mlYY1Lc4KiJ_iOfRk6dxYQ==/1442559255642204902.jpg')
    @blog_comment = Blogs::Comment.new
    @blog_comments = Blogs::Comment.where(blogs_post: @post).order(created_at: :desc)
    
  end

  private
  def create_params
    params.require(:blogs_post).permit(:content, :title, :sort_id)
  end
  def update_params
    params.require(:blogs_post).permit(:content, :sort_id)
  end
  def set_post
    @post = Blogs::Post.find(params[:id])
  end
  def set_blog_sort
    @sort = Blogs::Sort.new
  end
end

app/helpers/blogs/comments_helper.rb
module Blogs::CommentsHelper

end

app/helpers/blogs/post_sorts_helper.rb
module Blogs::PostSortsHelper
end

app/helpers/blogs/posts_helper.rb
module Blogs::PostsHelper

  #根据给出的@post 获取前一条数据
  def get_previous_one(current_post)
    raise if current_post.blank?
    return current_post if Blogs::Post.first.id >= current_post.id

    Blogs::Post.where('id < ?',current_post.id).last
  end
  #根据给出的@post获取后一条数据
  def get_after_one(current_post)
    return false if current_post.blank?
    return current_post if Blogs::Post.last.id <= current_post.id
    Blogs::Post.where('id > ?',current_post.id).limit(1)[0]
  end

end

app/views/blogs/posts/_add_post_sort_dialog.html.erb
<a tabindex="0" class="btn btn-lg btn-danger" role="button"
   data-toggle="popover"  title="新建博客分类"
   data-html="text"
   data-placement="top"
   data-content='
   <%= form_for @sort, url: blogs_post_sorts_path, method: :post,remote: true, data: {type: 'json'},authenticity_token: 'your_external_token' do |f| %>
  <label>分类名</label>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>
　　'>可消失的弹出框</a>

<script>
    $(function () {
        $('[data-toggle="popover"]').popover()
    })

</script>

<%= form_for @sort, url: blogs_post_sorts_path, method: :post,remote: true, data: {type: 'json'},authenticity_token: 'external_token' do |f| %>
  <label>分类名</label>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/blogs/posts/_title_style.html.erb
<!--http://zpfx2009.blog.163.com/blog/static/95058798200931471243764/-->
<% default_image_url = "http://img.blog.163.com/photo/zcxiDUbwjNbeKuvtpTAczQ==/1442559255642204898.jpg" %>
  <P style="TEXT-INDENT: 2em;"  >&nbsp;
  <TABLE height="70" width="525" class="<%= title_style.class_style %>">
    <TBODY>
    <TR>
      <TD vAlign="center" align="middle" background=<%=title_style.title_image_url.presence || default_image_url %> >
        <P></P>
        <P style="TEXT-INDENT: 2em;" class="title"  ><%=title_style.title_content.presence || '无标题' %></P>
      </TD>
    </TR>
  </TABLE>
  </P>

app/views/blogs/posts/index.html.erb
<%= content_for :title, '博客列表' %>

<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <h1>文章</h1>
      <% @posts.each do |post|
      next if post.title.blank?
      %>
        <div>
          <h5>2015-02-29 <small>分类：闲谈</small></h5>
          <h4><a href="<%= blogs_post_path(post) %>"><%= post.title %></a></h4>
        </div>
      <% end if @posts.length > 0 %>
    </div>
    <div class="col-lg-2">

    </div>
  </div>
</div>

app/views/blogs/posts/new.html.erb
<%= stylesheet_link_tag params[:controller] %>
<%= content_for :title,@post.new_record? ? '创建博客文章' : '更新' %>
<div class="container">
  <div class="row">
    <%= form_for @post ,html: {class: 'post_new_or_edit'} do |f| %>
    <div class="row">
      <div class="col-lg-12" style="text-align: center; align-content: center;padding-top: -30px;">
        <!---->

        <label class="title">标题：</label>
        <%= f.text_field :title, class: 'blog-title', size: '30', maxlength: '30', min: '1', placeholder: '必填，长度为1-30字。' %>
      </div>
    </div>
    <div class="col-lg-10 col-lg-offset-1">
          <%= render partial: "shared/wysiwyg-rails/editor", locals: {content: @post.content} %>

        <%= f.hidden_field :content,class: 'post_content' %>

          <script >
            //提交时将编辑器中的内容放入表单中。
            $(function(){
                form_submit_get_cus_content('.post_new_or_edit','.post_content')
            })
          </script>
    </div>
        <div class="col-lg-10 col-lg-offset-1">
          <h5><label>博客分类：</label><%= select_tag "blogs_post[sort_id]" ,options_from_collection_for_select(@post_sorts, :id, :name,(@post.sort_id unless @post.blank?) ),class: 'cus_select' %>
            <a href="<%= new_blogs_post_sort_path %>">添加</a>
          </h5>
          <%= f.submit %>

        </div>

  <% end %>

  </div>


</div>

<script>
  $(document).ready(
          function(){
              $('.post_new_or_edit').submit(function(){
                 var $title_value =  $('.blog-title').val()
                  if($title_value=='' || $title_value==null){
                      alert('对不起，请输入标题！')
                      return false;
                  }
                  return true;
              })
          }
  )

</script>

app/views/blogs/posts/show.html.erb
<%#= stylesheet_link_tag params[:controller] %>
<%= stylesheet_link_tag 'blogs/_posts_show' %>
<%= javascript_include_tag params[:controller] %>
<%= content_for :title, @post.title %>
<%= content_for :hidden_header_navi, true %>

<div class="container">
  <div class="row blog-content">
    <div class="col-lg-10 col-lg-offset-1">
      <div class="row title-row" >
        <div class="col-lg-10">
          <%= render partial: 'blogs/posts/title_style', object: @title %>
          <div class="subtitle">
            <h6>分类: <a href=""><%= @post.blogs_sort.present? ? @post.blogs_sort.name : '未分类' %></a>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
             创建时间 <%= datetime_format_helper(@post.created_at) %>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              最后修改于 <%= datetime_format_helper(@post.updated_at) %>
            </h6>
          </div>
        </div>
        <div class="col-lg-2">
          <!-- Split button -->
          <div class="btn-group">
            <button type="button" class="btn btn-default">操作</button>
            <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="caret"></span>
              <span class="sr-only">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu">
              <li><a href="<%= root_url %>">首页</a></li>
              <li><a href="<%= edit_blogs_post_path %>">修改</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">转载</a></li>
            </ul>
          </div>
        </div>

      </div>
      <div class="col-lg-12">
        <div id="preview" class="fr-view cus_show_blog"></div>
      </div>

    </div>
  </div>

  <script>
     $(function(){
         var content_code = "<%=@post.content%>"
         var content = $('#preview').html(content_code).text();

         $('#preview').html(content);
     })
  </script>

  <div class="row">
    <div class="col-lg-10 col-lg-offset-1 blog-content-foot">
      <% previous = get_previous_one(@post)
         after = get_after_one(@post)
      %>
      <h6> ↞ 上一篇:　<a href="<%= blogs_post_path(previous) %>"><%= previous.id == @post.id ? '【没有了】' : previous.title %></a></h6>
      <h6> ↠ 下一篇:　<a href="<%= blogs_post_path(after) %>"><%= after.id == @post.id ? '【没有了】' : after.title %></a></h6>
    </div>
  </div>

  <div class="container">
    <div class="row blog-comments">
      <h3>评论</h3>
        <% @blog_comments.each do |comment|
        next if comment.comment_content.blank?
        %>
        <div class="col-lg-10 col-lg-offset-1 blog-comment">
          <h5 class="email"><strong><%= comment.user.blank? ? '【游客】' : comment.user.email %></strong></h5>

          <h6><%= datetime_format_helper(comment.created_at) %></h6>
          <h5 class="louceng">＃<%= comment.id %></h5>

            <div><%= comment.comment_content %></div>
        </div>
          <% end if @blog_comments.length > 0 %>
    </div>

    <div class="row">
      <div class="col-lg-10 col-lg-offset-1">
        <div class="row">
          <div class="col-lg-12">
            <label><h3>发表看法：</h3><%= cus_current_user_email %></label>
          </div>
          <%= form_for @blog_comment, url: blogs_post_comments_path(@post), html: {class: 'comment'},
                       remote: true, data: {confirm: '确定提交此评论？', type: 'json'} do |f| %>

              <div class="col-lg-12">

                <%= f.text_area :comment_content, rows: '8', cols: '80',class: 'cc', maxlength: '1000', placeholder: '您的看法是？' %>
              </div>
              <div class="col-lg-12">
                <input type="checkbox" name="memory" id="memory" class="memory">　<label>请尽量记住我</label>
              </div>
              <!-- data: {disable_with: 'save...'}
               其实转换为
               data-disable-with='save...'
               -->
              <div class="col-lg-12">
                <%= f.submit '以上，这是我的观点', data: {disable_with: '正在提交中......'} %>
              </div>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</div>
<script>
$('form.comment').submit(function(){
    if(<%= current_user.blank? %>){
        alert('请先登录！')
        return false;
    }
   if($('textarea.cc').val()!=''){
       return true;
   }else{
       alert('留言不能为空！')
       return false;
   }
})
</script>